ahawker/ulid

tests/test_api.py, ulid/api.py, ulid/hints.py
=> Support Timestamp/ULID model types in api.from_timestamp.

README.md, tests/test_api.py, tests/test_ulid.py, ulid/api.py, ulid/ulid.py
The only two calls that remain functions instead of properties is `ULID.timestamp` and `ULID.randomness`.
=> Refactor model representation methods to be properties.

Makefile, requirements/base.txt, ulid/base32.py, ulid/hints.py, ulid/ulid.py
=> Add mypy static analysis support.

requirements/base.txt, requirements/codeclimate.txt, requirements/dev.txt, requirements/docs.txt, requirements/test.txt, requirements/tox.txt, requirements/travis.txt
Fixes #29.
The version of the "coverage" dependency is still variable due to
a regression in the latest version that breaks coverage reporting
for Codeclimate.
=> Pin all requirements to latest versions (if usable).

.travis.yml, Makefile, tox.ini
* Renames 'security-check' target to 'scan'.
* Removes 'scan' target from default Travis CI 'travis-script' target.
* Include new Travis CI job for 'scan' TOXENV.
=> Refactor security scan into separate Travis CI job.

tests/conftest.py, tests/test_base32.py
This PR contains some general naming refactoring
(non-ascii vs. extended-ascii) and fixes those tests
to assert on the correct code path exception.
Fixes #61
=> Fix non-ascii character set tests

tests/test_api.py, tests/test_base32.py, tests/test_ulid.py
This change promotes correctness to remove the risk of same
exception type asserts firing even though the incorrect code
path was actually tested.
Fixes https://github.com/ahawker/ulid/issues/65
=> Refactor tests to assert on exception messages.

.travis.yml, setup.py, tox.ini
If merged, this will include Python 3.7 as a supported version
for the package.
=> Add Python 3.7 Support

.travis.yml
Per official TravisCI communications, this is currently the proper way
to support py3.7. It's added as a separate matrix build so all builds
aren't set to use sudo: true and can run in container environments.
See: https://github.com/travis-ci/travis-ci/issues/9815
=> Switch from 3.7-dev to 3.7 on xenial.

.pylintrc, tests/conftest.py, tests/test_api.py, ulid/api.py
Status: **WIP**
If merged, this PR fixes #313.
The 'from_value' method should take a value of any supported type
and make a best guess attempt to convert it to a ULID instance.
Callers should only use this method when they're confident that they've
received a value that can be represented as a ULID but are unsure what
format/type it is in.
Callers should use the other from_* methods when the type/format is known.
=> Add 'parse' to public API

MANIFEST.in
It is required for a bdist_wheel, and it is useful to be able to do this from an sdist. pip does this to cache wheels.
Without this, from an sdist, I get:
```
$ python3 setup.py bdist_wheel
Warning: 'classifiers' should be a list, got type 'tuple'
running bdist_wheel
The [wheel] section is deprecated. Use [bdist_wheel] instead.
running build
running build_py
creating build/lib
creating build/lib/ulid
copying ulid/__init__.py -> build/lib/ulid
copying ulid/api.py -> build/lib/ulid
copying ulid/base32.py -> build/lib/ulid
copying ulid/hints.py -> build/lib/ulid
copying ulid/ulid.py -> build/lib/ulid
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
running install_egg_info
running egg_info
writing ulid_py.egg-info/PKG-INFO
writing dependency_links to …
```
=> Include the LICENSE in sdists

requirements/dev.txt, requirements/test.txt
This should fix broken Travis builds that are failing to find pylint 2.4.2 for py3.4.
=> Freeze pylint/pytest for py34 as its now deprecated

.travis.yml
There are now multiple py3.7 builds running in travis, so this simple tag condition would run on multiple jobs, causing multiple deployments, causing all subsequent ones to fail.
=> Change travis deploy version to 3.7 so there aren't duplicates

setup.py
ulid-py has `py.typed` but not included in built package because of invalid `package_data` path in `setup.py`.
It cause mypy error.
```python
import ulid
print(ulid.new())
```
```
ulid_sample/a.py:1: error: Skipping analyzing 'ulid': found module but no type hints or library stubs
```
before:
```
$ python setup.py build
Warning: 'classifiers' should be a list, got type 'tuple'
running build
running build_py
creating build
creating build/lib
creating build/lib/ulid
copying ulid/__init__.py -> build/lib/ulid
copying ulid/api.py -> build/lib/ulid
copying ulid/base32.py -> build/lib/ulid
copying ulid/hints.py -> build/lib/ulid
copying ulid/ulid.py -> build/lib/ulid
```
after:
```
$ python setup.py build
Warning: 'classifiers' should be a list, got type 'tuple'
running build
running build_py …
```
=> fix py.typed path

Makefile, ulid/hints.py, ulid/ulid.py
If merged, this PR makes the changes necessary to support `mypy --strict` and updates the Makefile target to run in strict mode as part of CI.
Fixes #450
=> Support mypy strict

ulid/__init__.py
If merged, makes additional changes to support `mypy --strict` for using the package public API.
Fixes #450
=> Explicitly define public api in __init__.py

tests/test_api.py, tests/test_bugs.py, tests/test_ulid.py, ulid/ulid.py
If merged, this PR adds support for pickling `MemoryView` instances, which includes `Randomness`, `Timestamp`, and `ULID`.
Fixes #452
=> Add pickle support

README.md, tests/test_ulid.py, ulid/ulid.py
If merged, this PR adds support for the `bin`, `oct`, and `hex` properties on the `MemoryView` class. It also implements `__index__` so it can be transparently converted with the global python functions.
```python
>>> import ulid
>>> u = ulid.new()
>>> u.bin
'0b1011100111101010011010110101011010111011010010011101011101001111010000101001010011100000100100011101011000011111000001101'
>>> bin(u)
'0b1011100111101010011010110101011010111011010010011101011101001111010000101001010011100000100100011101011000011111000001101'
>>> u.hex
'0x173d4d6ad7693ae9e8529c123ac3e0d'
>>> hex(u)
'0x173d4d6ad7693ae9e8529c123ac3e0d'
>>> u.oct
'0o13475232653273223535172051234044353037015'
>>> oct(u)
'0o13475232653273223535172051234044353037015'
```
=> Add support for bin, oct, and hex representations

requirements/dev.txt
Revert when https://github.com/timothycrosley/isort/issues/1273 and https://github.com/PyCQA/pylint/pull/3725 are closed.
=> Freeze isort to 4.x on py36

tests/test_api.py, tests/test_codec.py, ulid/__init__.py, ulid/api.py, ulid/base32.py, ulid/codec.py, ulid/hints.py
**Status:** WIP
If merged, this adds the `create` function to the API and constants for min/max randomness values.
The goal of this PR is to make it easier to create ULID values for range queries, e.g.
```python
timestamp = time.time()
value = ulid.create(timestamp, ulid.MAX_RANDOMNESS)
```
Fixes #457 
**TODO:**
=> Add API create method and min/max constants

tests/conftest.py, tests/test_base32.py, ulid/base32.py
If merged, this PR adds validation checks to raise ValueError when decoding ULID values that will overflow 128 bits.
Fixes #468 
```python
>>> import ulid
>>> ulid.parse('7ZZZZZZZZZZZZZZZZZZZZZZZZZ')
<ULID('7ZZZZZZZZZZZZZZZZZZZZZZZZZ')>
>>> ulid.parse('8ZZZZZZZZZZZZZZZZZZZZZZZZZ')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/hawker/src/github.com/ahawker/ulid/ulid/api.py", line 85, in parse
return from_str(value)
File "/Users/hawker/src/github.com/ahawker/ulid/ulid/api.py", line 190, in from_str
return ulid.ULID(base32.decode_ulid(value))
File "/Users/hawker/src/github.com/ahawker/ulid/ulid/base32.py", line 251, in decode_ulid
encoded = str_to_bytes(value, 26)
File "/Users/hawker/src/github.com/ahawker/ulid/ulid/base32.py", line …
```
=> Add MSB validation to raise when timestamp overflows 128 bits

.travis.yml, tests/test_providers_time_base.py, tests/test_providers_time_default.py, tests/test_providers_time_nanosecond.py, ulid/api/api.py, ulid/providers/base.py, ulid/providers/default.py, ulid/providers/monotonic.py, ulid/providers/time/__init__.py, ulid/providers/time/base.py, ulid/providers/time/default.py, ulid/providers/time/nanosecond.py
This adds two provider implementations using the following:
* time.time()
* time.time_ns()
If running on py37+, time.time_ns() will be used as it provides a
more accurate clock resolution according to https://www.python.org/dev/peps/pep-0564/#annex-clocks-resolution-in-python.
<blockquote><img src="https://www.python.org/static/opengraph-icon-200x200.png" width="48" align="right"><div><img src="/static/favicon.ico" height="14"> Python.org</div><div><strong><a href="https://www.python.org/dev/peps/pep-0564/">PEP 564 -- Add new time functions with nanosecond resolution</a></strong></div><div>The official home of the Python Programming Language</div></blockquote>
=> Add time providers to ulid.providers.time package

tests/test_api_api.py, tests/test_api_default.py, tests/test_api_microsecond.py, tests/test_api_monotonic.py, tests/test_providers_default.py, tests/test_providers_microsecond.py, tests/test_providers_monotonic.py, tests/test_providers_package.py, tests/test_providers_time_default.py, tests/test_providers_time_nanosecond.py, ulid/__init__.py, ulid/api/api.py, ulid/api/default.py, ulid/api/microsecond.py, ulid/providers/__init__.py, ulid/providers/base.py, ulid/providers/microsecond.py
The microsecond provider uses more precise clock resolution to
create randomness values that should monotonically increase on
timestamp (millisecond) collision.
When creating a new ULID, we extract the number of microseconds from
our timestamp and use them as the first two bytes of the randomness value.
Caveats:
When using `ulid.from_timestamp`, we fallback to the default implementation
of 10 bytes of pure randomness. The reason for this, is that the timestamp
that is being passed in by the caller is in milliseconds. Since we don't have
a more accurate timestamp to "steal" bytes from, there's not much we can do. We
cannot make a new epoch timestamp as the microsecond remainder is only accurate
when working within the same millisecond.
If merged, this adds a microsecond …
=> Add microsecond provider

README.md
Hi, thanks for the nice ULID lib
The docs appear to be a bit out-of-sync with the implementation. [`timestamp().datetime` is set up to always return a UTC datetime](https://github.com/ahawker/ulid/blob/v1.1.0/ulid/ulid.py#L265-L267) (that's good!) but the docs don't reflect that. This PR fixes the docs to match that implementation.
Cheers, thanks again for the project
=> Update/fix docs: timestamp().datetime always returns a UTC datetime
